### ISSUE TITLE
Fix Documentation Error in _all.yml

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coAST#23]
The word `currently` has been repeated twice on line 10 of the file  `_all.yml`

`# 'block' currently currently implies a new 'scope', however we may need to`

Label:- difficulty/newcomer

**Comment by BinaryGears** [comment]
I have fixed the issue on my local branch and am interested in pushing the change.

**Comment by p-murli** [comment]
Hey, is this issue still open and can I submit a PR?

**Comment by BinaryGears** [comment]
I'm planning on doing it if they let me. I will join the gitter when I get
off work tonight.

**Comment by BinaryGears** [comment]
p-murli has already fixed the issue.

**Comment by li-boxuan** [comment]
Closed by https://github.com/coala/coAST/pull/24
