### ISSUE TITLE
D.yaml: Fix `delimters` spelling

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coAST#69]
The file `D.yaml` has a spelling mistake at line [10](https://github.com/coala/coAST/blob/master/data/Language/D.yaml#L10)

The `delimter` should be changed to `delimiter`

label: difficulty/newcomer

**Comment by kapurm17** [comment]
Hi @Naveenaidu , can I be assigned this issue ?
Although I haven't received the invite yet, I'd like to work on this issue and I'll send the pull request later when I'll recieve the invite.
Can I work on this?

**Comment by CleverFool77** [comment]
I want to work on this issue.

**Comment by utkarsh2102** [comment]
@CleverFool77, please don't make a PR unless you have been assigned.
Technically, @kapurm17 should be assigned this issue.

**Comment by rajgoesout** [comment]
I guess this issue can be closed, because it's already fixed.

**Comment by GeniusLearner** [comment]
Hi, @RJ722
I have verified that this issue been resolved. So please close it.

**Comment by RJ722** [comment]
Thanks for infomrming!
