### ISSUE TITLE
Grammar file produces a hyperlink even when no value is given to it in the Language files

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coAST#70]
Grammer file produces a hyperlink to the respective grammar files when we provide the entry to it in the language file. 

Example:- [C.yaml](https://github.com/coala/coAST/blob/master/data/Language/C.yaml#L4)
`grammar_file: https://github.com/antlr/grammars-v4/blob/master/c/C.g4`

After the site is deployed, the results are rendered as: https://coast.netlify.com/c/
As you see here a hyperlink is produced for the grammar file.

*But*

When the `grammar file` field is empty or not mentioned in the language file such as [Bash.yaml](https://github.com/coala/coAST/blob/master/data/Language/Bash.yaml) or [Swift.yaml](https://github.com/coala/coAST/blob/master/data/Language/Swift.yaml) where the grammar file is not present.

When these files get [rendered](https://coast.netlify.com/bash/), they display the text `None` which hyperlinks to a page which do not exist.

Grammar File | [None](https://coast.netlify.com/bash/None)
-- | --

This needs to be fixed. Instead of showing None with a hyperlink. It should only show `None` without any hyperlinks.

label: difficulty/low

**Comment by rajdeepbharati** [comment]
Can I work on this issue?
