### ISSUE TITLE
Swift.yaml: Add `grammar_file`

### ISSUE THREAD

**Issue by utkarsh2102** [coala/coAST#77]
[Swift.yaml](https://github.com/coala/coAST/blob/master/data/Language/Swift.yaml) presently has no `grammar_file` mentioned.
However, this exists. Link: https://github.com/antlr/grammars-v4/blob/master/swift3/Swift3.g4

Please add this link in `grammar_file` as is done in other languages, like, [C](https://github.com/coala/coAST/blob/master/data/Language/C.yaml), etc.

A good `newcomer` issue.

**Comment by utkarsh2102** [comment]
@jayvdb, this would be a `newcomer` issue.
Please remove `difficulty/low` from it :)

**Comment by naveentvelu** [comment]
Can I take up this issue?

**Comment by utkarsh2102** [comment]
@naveentata, only work on the issue when you are assigned. Please don't open any unnecessary PRs.
