### ISSUE TITLE
VisualBasic.yaml: Line length for `grammar_file` needs to be reduced

### ISSUE THREAD

**Issue by utkarsh2102** [coala/coAST#78]
In [VisualBasic.yaml](https://github.com/coala/coAST/blob/master/data/Language/VisualBasic.yaml):
https://github.com/coala/coAST/blob/01100420e6129171bbbaed99deb7e9cb3ac0040b/data/Language/VisualBasic.yaml#L5
The above line length (82) exceeds the maximum length, which is 79.
It'd be better if we shift this to a new line as is done in other files.

A good `newcomer` issue.

**Comment by naveentvelu** [comment]
Can this issue assigned to me?

**Comment by utkarsh2102** [comment]
@naveentata, only work on the issue when you are assigned. Please don't open any unnecessary PRs.

**Comment by li-boxuan** [comment]
Solved by https://github.com/coala/coAST/commit/e13f222044f840e1d9c7bbccf66187332cd88f2f
