### ISSUE TITLE
Pascal.yaml: Add declared `datatypes` to `data/DataType`

### ISSUE THREAD

**Issue by utkarsh2102** [coala/coAST#79]
The `datatypes` mentioned under [Pascal.yaml](https://github.com/coala/coAST/blob/master/data/Language/Pascal.yaml)
https://github.com/coala/coAST/blob/01100420e6129171bbbaed99deb7e9cb3ac0040b/data/Language/Pascal.yaml#L74-L79
haven't been declared under `data/DataType` [here](https://github.com/coala/coAST/tree/master/data/DataType).

A good `difficulty/low` issue.

**Comment by jayvdb** [comment]
We have a generic GCI task for doing this, so we dont want specific issues for each language
